"""Add information assets and risk matrix

Revision ID: 856e3d2521dd
Revises: 20260528_audit_ip_guide_fields
Create Date: 2026-06-17 02:52:43.375984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856e3d2521dd'
down_revision: Union[str, Sequence[str], None] = '20260528_audit_ip_guide_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('confidentiality', sa.Integer(), nullable=True),
    sa.Column('integrity', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=120), nullable=True),
    sa.Column('created_by_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_assets_id'), 'information_assets', ['id'], unique=False)
    op.create_unique_constraint('_usuario_animal_uc', 'animalfavorito', ['usuario_id', 'animal_id'])
    op.create_index(op.f('ix_historial_medico_veterinario_id'), 'historial_medico', ['veterinario_id'], unique=False)
    op.create_index(op.f('ix_onboarding_tour_progress_user_id'), 'onboarding_tour_progress', ['user_id'], unique=False)
    op.create_unique_constraint('uq_onboarding_tour_progress_user_tour', 'onboarding_tour_progress', ['user_id', 'tour_key'])
    op.create_index('idx_password_history_user_created', 'password_history', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_password_history_user_id', 'password_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_history_id'), 'password_history', ['id'], unique=False)
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_password_history_user_id_users'), 'password_history', type_='foreignkey')
    op.create_foreign_key(None, 'password_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('risk_matrix_entries', sa.Column('information_asset_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_risk_matrix_entries_created_by_id'), 'risk_matrix_entries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_risk_matrix_entries_updated_by_id'), 'risk_matrix_entries', ['updated_by_id'], unique=False)
    op.create_foreign_key(None, 'risk_matrix_entries', 'information_assets', ['information_asset_id'], ['id'])
    op.create_index(op.f('ix_tarea_usuario_asignado_id'), 'tarea', ['usuario_asignado_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_permission', 'user_permissions', ['user_id', 'permission_id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint('uq_user_permission', 'user_permissions', type_='unique')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_tarea_usuario_asignado_id'), table_name='tarea')
    op.drop_constraint(None, 'risk_matrix_entries', type_='foreignkey')
    op.drop_index(op.f('ix_risk_matrix_entries_updated_by_id'), table_name='risk_matrix_entries')
    op.drop_index(op.f('ix_risk_matrix_entries_created_by_id'), table_name='risk_matrix_entries')
    op.drop_column('risk_matrix_entries', 'information_asset_id')
    op.drop_constraint(None, 'password_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_password_history_user_id_users'), 'password_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_id'), table_name='password_history')
    op.drop_index('idx_password_history_user_id', table_name='password_history')
    op.drop_index('idx_password_history_user_created', table_name='password_history')
    op.drop_constraint('uq_onboarding_tour_progress_user_tour', 'onboarding_tour_progress', type_='unique')
    op.drop_index(op.f('ix_onboarding_tour_progress_user_id'), table_name='onboarding_tour_progress')
    op.drop_index(op.f('ix_historial_medico_veterinario_id'), table_name='historial_medico')
    op.drop_constraint('_usuario_animal_uc', 'animalfavorito', type_='unique')
    op.drop_index(op.f('ix_information_assets_id'), table_name='information_assets')
    op.drop_table('information_assets')
    # ### end Alembic commands ###
